# -*- coding: utf-8 -*-
"""GDP_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19l9ZYTeijJVYA1r9K6vHJNPGNoIQTKp0

## 1 ).Loading  the Dateset
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
df = pd.read_csv('gdp.csv')
df

"""## check the null value

"""

df.info()

df.isnull().sum()

"""## check Description of each column"""

df['Country Name'].describe()

df['Country Code'].describe()

df['Value'].describe()

df['Year'].describe()

df['Year'].min()

df['Year'].max()

"""# 2 Data Analysis

###2.1).Analysis Arab World
"""

df [df['Country Name']== 'Arab World'	]

df_pr = df [df['Country Name']== 'Arab World'	]

""" ### 2..2) Caluclate the GDP growth of Arab World	& Assign value

"""

df_pr.values

data = df_pr.values

gdp_change =[0]

for i in range(1,len(data)):
   #print(data[i-1][3]-data[i][3])

     prev = data[i-1][3]
     cur = data[i][3]

     gdp_change.append(round(((cur - prev) / prev)*100,2))
gdp_change

df_pr.assign(GDP = gdp_change)

df_whole_data = df
df_whole_data

"""### 2.3) Finding GDP Growth of Every Country"""

final_data=[]
for country in df['Country Name'].unique():
  df_pr = df [df['Country Name']== country]
data = df_whole_data.values
gdp_change =[0]
for i in range(1,len(data)):
   #print(data[i-1][3]-data[i][3])
     prev = data[i-1][3]
     cur = data[i][3]
     gdp_change.append(round(((cur - prev) / prev)*100,2))
gdp_change
final_data.append(gdp_change)

df_whole_data = df_whole_data.assign(GDP = gdp_change)
df_whole_data

df = pd.concat([df_whole_data],axis=0)

df.head()

"""### 2.4) Finding  the Maximum GDP Growth of each & every country

"""

df.groupby('Country Name').max()['GDP'].sort_values(ascending = False).head(10)

"""###2.5) Finding the Minmum GDP Growth of each & every country"""

df.groupby('Country Name').min()['GDP'].sort_values(ascending = False).head(10)

"""### 2.6) Overall GDP according to their Value of the country"""

df.groupby('Country Name').max()['Value'].sort_values(ascending = False).head(50)

df

"""#3) Plotting  the Graph Using Plotly

###3.1) GDP Analysis to the World
"""

df_pr = df[df['Country Name']=='World']
fig = px.line(df_pr, x='Year', y='Value', title='World GDP Analysis')
fig.show()

"""###3.2) GDP Analysis to the India"""

df_pr = df[df['Country Name']=='India']
fig = px.line(df_pr, x='Year', y='Value', title='India GDP Analysis')
fig.show()

"""###3.3)GDP of top 20 Country"""

import plotly.express as px
top_countries = df.groupby('Country Name')['Value'].max().sort_values(ascending=False).head(20).index
filtered_df = df[df['Country Name'].isin(top_countries)]
fig = px.bar(filtered_df, x='Country Name', y='Value', color='Year',
             title='GDP of Top  20 Countries ')
fig.show()

"""###3.4) GDP of all Countries"""

import plotly.express as px
fig = px.line(df, x='Year', y='Value', color='Country Name', title='GDP of All Countries ')
fig.show()

"""###3.5) GDP  Growth Comparison between India & China"""

c1 = df[df['Country Name'] == 'India']
c2 = df[df['Country Name'] == 'China']
c1.head()

c2.head()

df_pr = pd.concat([c1, c2], axis=0)
df_pr

fig = px.line(df_pr, x='Year', y='Value', color='Country Name', title='GDP Comparison between India & China')
fig.show()

"""### 3.6) GDP  Growth Comparison between India & United States"""

c1 = df[df['Country Name'] == 'United States']
c2 = df[df['Country Name'] == 'India']
df_pr = pd.concat([c1, c2], axis=0)
fig = px.line(df_pr, x='Year', y='Value', color='Country Name', title='GDP Comparison between India & China')
fig.show()

"""###3.7) GDP Growth Comparison  b/w Specific Countries"""

lst =['IND', 'ITA','USA','CHN']
dfs=[]
for i in lst:
  dfs.append(df[df['Country Code']==i])
  df_pr =pd.concat(dfs,axis=0)
fig = px.line(df_pr, x='Year', y='Value', color='Country Name', title='GDP Comparison ')
fig.show()

"""###3.8) GDP Growth  between 1960 to 2016"""

dfs = []
for country_name in df['Country Name'].unique():
  df_pr = df[df['Country Name']==country_name]

  if(len(df_pr)==57):
    dfs.append(df_pr)
df_pr = pd.concat(dfs,axis=0)
fig = px.line(df_pr, x='Year', y='GDP', title='GDP Growth ',color='Country Name')
fig.show()

